### ISSUE TITLE
优化标签样式的建议

### ISSUE THREAD

**Issue by JOYCELEEEEE** [chenshinshi/toy#1]
![image](https://github.com/chenshinshi/toy/assets/89592448/b8b0fa69-c10b-460b-a999-2a3d0ff1b9ae)

标签样式看起来几乎和下划线一样，能否优化一下呢，类似于savor的就不错：
![image](https://github.com/chenshinshi/toy/assets/89592448/79eb802a-eda3-4b49-9a9d-8ce0a8729874)

最后感谢您的主题，很简约很好看！

**Comment by chenshinshi** [comment]
收到，下个版本更新！
