### ISSUE TITLE
P-Book主题有一个类似笔记本格子的底图删除了吗？

### ISSUE THREAD

**Issue by xy0124** [chenshinshi/toy#10]
更新后没有了，一直用那个，觉得喜欢。或者说有没有方式提供底图替换？

**Comment by xy0124** [comment]
<img width="977" alt="598577bed4c13c390c4993de6c9a04c" src="https://github.com/chenshinshi/toy/assets/99000021/9be70415-5424-43b6-99a6-a85e3831be36">
找到曾经的一个笔记截图

**Comment by chenshinshi** [comment]
撤掉的原因是觉得有点杂乱，如果需要的人多的话我再加进去，最近有点忙。

**Comment by chenshinshi** [comment]
.p {
    /* box-shadow: 0px 1px 0px 0px rgb(239 230 201); */
    padding-bottom: 0px !important;
/*    border-bottom: 2px dashed rgba(186, 146, 157, 0.4); */
background: linear-gradient(
    to right,
    transparent 0%,
    transparent 50%,
    rgba(186, 146, 157, 0.8) 50%,
    rgba(186, 146, 157, 0.8) 100%
  );
  background-size: 7px 1px;
  background-repeat: repeat-x;
  background-position-y: bottom;
}

**Comment by chenshinshi** [comment]
需要的话加这段代码

**Comment by xy0124** [comment]
OK.谢谢。
加在代码片段
![image](https://github.com/chenshinshi/toy/assets/99000021/d1b85eb5-9e52-4ea3-a90a-893ba4e11cb2)
…………
已经成功，谢谢。加上后配合主题就很完美了。纯粹个人审美取向
