### ISSUE TITLE
宽度未按照软件设置，PDF导出主题丢失以及代码块与行号之间有间隙

### ISSUE THREAD

**Issue by ghost** [chenshinshi/toy#12]
1. 主题配色非常好看。
2. 思源软件中关闭了自适应宽度，但是应用toy主题后，这个设置不生效了。无论开或关，文档都是撑满屏幕的，正常情况下，关闭自适应宽度后，文档样式类似A4纸的宽度。
3. 导出PDF的时候，主题样式没有渲染出来，不论切换到哪种配色，导出PDF的时候，都是白底黑色，点缀色是绿色。

**Comment by ghost** [comment]
![image](https://github.com/chenshinshi/toy/assets/39425860/6baa3812-46eb-4a62-bbdb-76bb1d7c9d6d)
关闭了自适应开关

![image](https://github.com/chenshinshi/toy/assets/39425860/1a648730-b1aa-4ea4-a407-bf76990e041d)
宽度还是没有缩小

![image](https://github.com/chenshinshi/toy/assets/39425860/ee9a919b-94fe-468d-94aa-b3a6a0eb735e)
切换到默认主题后，宽度变成普通word的宽度了。

**Comment by ghost** [comment]
![image](https://github.com/chenshinshi/toy/assets/39425860/c5f5bc03-3f13-4faf-8b2e-f59e5befb352)
导出pdf时，配色没有被应用。

**Comment by ghost** [comment]
![image](https://github.com/chenshinshi/toy/assets/39425860/e6d10de2-7509-410d-b5eb-ffe9690fbd87)
![image](https://github.com/chenshinshi/toy/assets/39425860/1da2cb7b-34a5-4467-94dc-5b9180804c7d)
然后每个主题的代码块，行号与代码之间，都有一条间隙。

**Comment by chenshinshi** [comment]
1. 感谢夸奖！
2. 填满屏幕的原因是为了让分屏显示时间隔不会过大浪费空间，你可以修改代码取消padding限制。
3. pdf导出的问题只能通过在theme.css文件夹手动将yinxiang.css改为你所使用的主题的css文件，因为主题配色切换不能应用于pdf导出，我平时则是浏览器打开思源软件然后使用浏览器插件导出pdf可以应用所见即所得的样式。

**Comment by chenshinshi** [comment]
4. 我不使用代码块不知道代码块本应该长什么样子，只做了行数对齐的适配，下个版本会尝试调整下，我在公告中推荐了插件商店中的代码块样式你可以尝试下。

**Comment by ghost** [comment]
通过你的修复和建议，问题基本都已经解决了，非常感谢
