### ISSUE TITLE
雨青的.b3-dialog__body少了个border-radius

### ISSUE THREAD

**Issue by WingDr** [chenshinshi/toy#13]
如题，.b3-dialog__container里面有border-radius，但是body里面没有，就会出现这种尖角的情况

![image](https://github.com/chenshinshi/toy/assets/63407442/4cdc3be8-e151-4356-8f50-f98354c5c4f8)

好像其它主题都是这样的，但是雨青的比较浅，突出来的角就特别明显

**Comment by chenshinshi** [comment]
收到，这几天没怎么用思源，过几天适配下

2023年8月2日(水) 16:59 WingDr ***@***.***>:
