### ISSUE TITLE
移动端缺少切换子主题的按钮

### ISSUE THREAD

**Issue by WingDr** [chenshinshi/toy#14]
如下图，iPad上没有切换子主题的按钮，回去之后再试试手机上有没有，但我感觉大概率也是无的

![bc83586784771a6fa3e4f02559e9012](https://github.com/chenshinshi/toy/assets/63407442/db8c909b-4d19-4e1e-a541-a716d69aaf2e)

**Comment by chenshinshi** [comment]
是没有的，因为我不会js不会修，主题迭代器不支持pdf导出也不支持移动端（readme已说明。），如果有需要只能手动引入文件，比如在代码片段里加import（

**Comment by chenshinshi** [comment]
https://github.com/chenshinshi/toy/assets/125173405/c6ccebed-3d20-43db-82a6-a8ac6d44cf0e

**Comment by WingDr** [comment]
懂了，我去研究一下，要是弄明白了就提个pr过来
