### ISSUE TITLE
为啥protyle-content上面加了40px的padding-top

### ISSUE THREAD

**Issue by WingDr** [chenshinshi/toy#16]
如下图，

![image](https://github.com/chenshinshi/toy/assets/63407442/540fb81a-a278-4c70-9050-7e4764617a5e)

平常在编辑器里看起来还好，但是一旦在其他地方用protyle，就会导致上面有一大块空白。这个是为了照顾到什么东西而做的特殊设计吗？

![image](https://github.com/chenshinshi/toy/assets/63407442/66fc8a00-3fd8-4edb-b8f7-63a837315383)

**Comment by chenshinshi** [comment]
是为了让面包屑那块不会空白，因为我的面包屑后面是想做文档穿过的透明效果。

**Comment by chenshinshi** [comment]
如果去掉后大纲定位还有悬浮窗的话内容就离面包屑有点近了，你是要在什么地方用啊可以对那个使用场景限定把这条去掉。

**Comment by WingDr** [comment]
> 如果去掉后大纲定位还有悬浮窗的话内容就离面包屑有点近了，你是要在什么地方用啊可以对那个使用场景限定把这条去掉。

主要是我用的地方我会把面包屑去掉emmmm CSS这块我不太熟，如果我在外面包一个特定class的div，怎么写能把这里面的这个样式改掉？

**Comment by chenshinshi** [comment]
.class .protyle-content {padding-top:0px;} 差不多是这样

**Comment by WingDr** [comment]
> .class .protyle-content {padding-top:0px;} 差不多是这样

解决了，非常感谢
