### ISSUE TITLE
可以优化一下编辑区顶部钉住 tab页的展现样式吗？

### ISSUE THREAD

**Issue by TopProgrammer** [chenshinshi/toy#17]
<img width="691" alt="image" src="https://github.com/chenshinshi/toy/assets/8543339/2de8c359-5c84-40fe-8efa-b7f4b6b13492">
当前主题外观非常 nice，但是tab 页在钉住之后不利于查看，希望大佬可以优化一下
<img width="883" alt="image" src="https://github.com/chenshinshi/toy/assets/8543339/46a73955-8d2a-4711-8383-c5cba2c63d48">

**Comment by chenshinshi** [comment]
我设想的使用场景是置顶后节省显示面积，如果需要看标签文字可以悬浮查看，如果你需要显示全宽可以注释掉这段代码。
.layout-tab-bar .item--pin {
   min-width:30px;
   max-width:30px;
   padding:0px;
}
.layout-tab-bar .item--pin .item__text {
   padding:0px;
}
