### ISSUE TITLE
从二级列表开始竖线就对不上了

### ISSUE THREAD

**Issue by WingDr** [chenshinshi/toy#2]
如图，有序列表、无序列表都这样，应该是向上偏了固定距离

![image](https://github.com/chenshinshi/toy/assets/63407442/7423ce0a-ad4e-4e7d-8f27-0fa2adf01119)

**Comment by chenshinshi** [comment]
欸我这边无法复现，怎么回事？

**Comment by chenshinshi** [comment]
![image](https://github.com/chenshinshi/toy/assets/125173405/c22b9f08-f147-451c-8e6c-0d2f6c1575bb)

**Comment by chenshinshi** [comment]
啊定位到问题了，是bearlight主题是吧，我后续修一下，收到
