### ISSUE TITLE
满白主题下链接样式的优化建议

### ISSUE THREAD

**Issue by JOYCELEEEEE** [chenshinshi/toy#3]
![演示](https://github.com/chenshinshi/toy/assets/89592448/c2c241d7-e06c-4b9c-8163-5283e97a4fb9)

不悬浮的话似乎和正常的文本没有区别

之前和满白类似的“冬”主题里的链接是蓝色的，感觉挺不错的

但是更新后冬主题好像找不到了

**Comment by chenshinshi** [comment]
收到，因为冬和fountain和满白相似所以我自作主张删掉了，下个版本更新！
