### ISSUE TITLE
toy主题-bearlight配色-网页视图插件-点击链接打开网页页面：只显示了一半的网页（其他配色不会）

### ISSUE THREAD

**Issue by otto88956** [chenshinshi/toy#5]
思源笔记版本号：
2.9.4
本地主题toy版本号：
v1.2.0
确认关闭其他代码片段后是否能重现问题：
是
问题描述：
toy主题-bearlight配色-点击链接打开网页页面：只显示了一半的网页
（主题的其他配色不会出现此问题）
复现步骤：
1、toy主题-bearlight配色-开启网页视图插件或web应用工具插件-点击链接打开网页页面：只显示了一半的网页
操作系统：
Mac OS 13
![image](https://github.com/chenshinshi/toy/assets/137133811/3661b0a8-ca80-4540-90ba-46ffa5042e78)

**Comment by chenshinshi** [comment]
收到，我说咋打不开微信读书了，下个版本修复
