### ISSUE TITLE
公告：P-Book移植；完善各主题

### ISSUE THREAD

**Issue by chenshinshi** [chenshinshi/toy#6]
P-Book已经移植到本主题，目前各面板的颜色没有和原主题统一，如果大家实在不习惯新面板可以复刻。
其他主题存在许多问题，如配色的醒目度和舒适度问题，还需要深度体验。

**Comment by mummer98** [comment]
请问以下代码块样式为什么不对啊，行号和代码对应不上
![image](https://github.com/chenshinshi/toy/assets/77563657/1a22ecf0-b430-430a-be2f-881ce334df5e)

**Comment by chenshinshi** [comment]
收到，下个版本适配，建议使用代码块美化插件，我是文科生不用代码块

**Comment by chenshinshi** [comment]
不要在公告帖评论提问。
