### ISSUE TITLE
引用块的图标排列问题

### ISSUE THREAD

**Issue by leipeng111** [chenshinshi/toy#7]
![QQ图片20230713090420](https://github.com/chenshinshi/toy/assets/42474642/f810d9bc-9490-44a1-82d0-848290f7abae)
多个子主题的引用图标和竖线重叠在一起了，建议分开来好看些

**Comment by chenshinshi** [comment]
因为bearlight的引用块是通过加伪元素实现的，不只是你说的悬浮块标重合问题，
![image](https://github.com/chenshinshi/toy/assets/125173405/0c8b76e0-ca43-4bc4-9781-2b9c6ea9b221)
他也会和无序列表重合。
![image](https://github.com/chenshinshi/toy/assets/125173405/801d29c2-0ffb-449b-a765-7fb0b2ab9b88)
正常是这样。
一开始是为了和bearlight的设计保持统一所以才将其他主题的引述块也改成这样了，还需要进一步征集意见，确实改成左边框然后加padding会更好些。

**Comment by leipeng111** [comment]
好的，期待主题做的越来越好用 ∩_∩
