### ISSUE TITLE
雨青的顶栏，没聚焦窗口的时候会变成黑色

### ISSUE THREAD

**Issue by WingDr** [chenshinshi/toy#8]
如图，还是说它本来就是黑的？主要是觉得有点突兀

![image](https://github.com/chenshinshi/toy/assets/63407442/5b054ed6-dce5-4b41-9fb7-70a5150308be)

**Comment by chenshinshi** [comment]
没想好怎么改，原主题是设置了blur color为黑，我其他都是设置成透明，你觉得有区别好还是无区别好？

**Comment by WingDr** [comment]
主要是标题栏的字的颜色不会自动变白，变黑之后啥都看不见基本只能盲点。所以我感觉还是先设置成透明吧，本身雨青的编辑器颜色比较浅，不聚焦的时候变浅也比较符合平常使用的直觉

**Comment by chenshinshi** [comment]
ok，下个版本更新！
