### ISSUE TITLE
大纲面板反馈| 标题过多时，末端标题被遮挡

### ISSUE THREAD

**Issue by JOYCELEEEEE** [chenshinshi/toy#9]
![Snipaste_2023-07-17_11-22-10](https://github.com/chenshinshi/toy/assets/89592448/901b6380-0cf2-4ad1-b504-69bb762aea4e)

如图，尝试拖动内侧和外侧的滚动条都没有效果。

官方主题没有这个问题。

您要是有空可以看一下🤗

**Comment by chenshinshi** [comment]
没遇到过，你方便把你的这份文件发给我测试吗？

**Comment by JOYCELEEEEE** [comment]
它是间歇的，一会能显示，一会又不能😂

等我找到了确定的方法后再来反馈，感谢您的回复！（issue先关了）

发件人: ***@***.***>
发送时间: 2023年7月18日 9:43
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [chenshinshi/toy] 大纲面板反馈| 标题过多时，末端标题被遮挡 (Issue #9)


没遇到过，你方便把你的这份文件发给我测试吗？
